### ISSUE TITLE
Enable processing of junit test reports

### ISSUE THREAD

**Issue by fml2** [swingletree-oss/swingletree#53]
It would be cool if there existed a plugin similar to https://github.com/swingletree-oss/plugin-testng that would be able to accept junit test reports and show them in some digested form (total number of tests, details about failed tests). A direct link from within a pool request to the swingletree view would make it even better.

**Comment by error418** [comment]
This functionality is handled by `plugin-nebula` (for gradle-based builds only). At the time this plugin does not write the test results to the check-run details, since it is lacking a report template for this purpose. `plugin-nebula` reports the amount of total and - if any occurred - skipped and failed tests.

### On TestNG

TestNG [is compatible][migrate] with JUnit tests and is shipped with Gradle.

> TestNG can automatically recognize and run JUnit tests, so you can use TestNG as a runner for all your existing tests and write new tests using TestNG.

You can enable it by following setting in your `build.gradle`:

```groovy
test {
  useTestNG()
}
```

The resulting report can then be processed with `plugin-testng`, which attaches a report to your check-run using this template: [plugin-testng/templates/report.md.tpl](https://github.com/swingletree-oss/plugin-testng/blob/master/templates/report.md.tpl). This template would cover the points you mentioned.

### Closing Thoughts

Using TestNG is a good decision to make. TestNG reports are a bit more detailled as their JUnit-counterparts and offers some very interesting features on top of JUnit, which you can look into on the [TestNG website][tng].

`plugin-testng` can provide a solution for TestNG as well as JUnit based tests (which get executed by TestNG). Using one plugin for test-report purposes reduces the maintenance load of swingletree and benefits therefore maintainers as well as swingletree users.


Was this helpful for you?


[tng]: https://testng.org/doc/index.html
[migrate]: https://testng.org/doc/migrating.html

**Comment by fml2** [comment]
I've just tried by including `test { useTestNG() }` into `build.gradle` but it did not work. The unit tests were not found. I must have done something wrong.

But even if it did work it would not be ideal since we'd have to adjust all our build scripts (include the useTestNG option since it's not the default).

I'll try again though.

**Comment by error418** [comment]
> I've just tried by including test { useTestNG() } into build.gradle but it did not work. The unit tests were not found. I must have done something wrong.

Please see the linked "Migrate from JUnit" section of the TestNG docs for further information about this topic

**Comment by fml2** [comment]
Would it be feasible to let the [testng plugin](https://github.com/swingletree-oss/plugin-testng) also process JUnit reports? I.e. recognize the report type by e.g. the root element of the report?

**Comment by error418** [comment]
It is planned to release a junit plugin as part of a [Sponsorware](https://github.com/sponsorware/docs) release. I'll keep you posted inside this issue - stay tuned :blush:

**Comment by error418** [comment]
This feature is now available via Sponsorware. More information can be found on the docs pages ( https://swingletree-oss.github.io/swingletree/docs/plugins/junit/ )
